version: '3'
services:
  java:
    container_name: javaApp
    build:
      context: .
      dockerfile: ./Dockerfiles/java/Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/public
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - "8080:8080"
    networks: 
      - container_network
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    ports: 
      - "5432:5432"
    networks: 
      - container_network
networks:
  container_network:
    driver: bridge  
